### ISSUE TITLE
Not UTF-8

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#13]
![Capture](https://user-images.githubusercontent.com/20246049/57589188-dec8f700-74f6-11e9-8470-67206e166189.PNG)

Can't write with latin diacritcs, as in "Platão".

**Comment by pjheslin** [comment]
I think several of the problems you have reported are a result of using a subcorpus name with non-ascii characters in it.  This is a bug.

**Comment by pjheslin** [comment]
I have tried to fix this, and it is surprisingly tricky (the internals of Diogenes are not utf-8, as it predates Unicode).  Creating filters with Latin, non-ascii names will sometimes display incorrectly (as here), but they should work correctly.  Greek filter names seem to display fine.  In all cases, the use of non-ascii filter names causes a warning about printing a wide character to be printed to the console (if you start Diogenes from the console). 

Since the non-ascii filters work just fine, and the display fix will be tricky, I am not going to prioritize fixing this at the moment.  I've put it on the long-term to-do list.
