### ISSUE TITLE
Proposal: display more intuitive initial values in new "Read" windows

### ISSUE THREAD

**Issue by telemachus** [pjheslin/diogenes#30]
Would you consider a pull request that changes the default values of a new "Read" window in the following ways?

1. Always display 1s initially.
2. Behave internally as if there were 0s there. (I.e., internally behave the way that 0s behave now.)
3. Remove the hint telling people to use 0s as initial values.

Here's my justification: at least some people are likely to miss the hint (cough, I did for several days); if people miss the hint and manually type in 1s, the app does things nobody actually wants (e.g., for Aeneid 1.1, the app shows you the end of the Georgics, with Aeneid 1.1 below).

Is there an edge case where someone would actually want the 1s behavior that I'm not thinking of?

**Comment by helmadik** [comment]
The feature is meant to deal with texts that start with some 1st section that is 'numbered' p (proem) (e.g.). Since users, even classicists, don't usually read instructions, one might re-do this screen with 2 options: Go to beginning of work. Or pick a different passage below:

**Comment by telemachus** [comment]
Ah, that helps me to understand it. Still, I'd like to figure out a way to have that first screen simply "do the right thing" in a wide variety of circumstances. I'm not yet sure what that would mean in practice, but I think it's worth considering. Your option of two choices is definitely good, but I wonder if it could be even simpler. I can't see how just yet, but...

**Comment by helmadik** [comment]
Be aware that Peter has dealt with these crazy databases for a long time.. Simply do the right thing is of course never simple, or even the right thing. Slight user interface change might work, though.

**Comment by telemachus** [comment]
> Be aware that Peter has dealt with these crazy databases for a long time.. Simply do the right thing is of course never simple, or even the right thing.

Again, fair enough.

> Slight user interface change might work, though.

A thought: what if we remove the hint and enter an initial value of *beginning* instead? (Or, perhaps, I should just admit that I need to read instructions better and let this go.)

**Comment by pjheslin** [comment]
To use the old chestnut, this is not a bug but a feature.  It may not be a feature you like or use, but you can be sure that some people need it.  As Helma has explained, there are some texts with proemial material at the start of the text or of individual sections that can be quite extensive.  I needed to provide a way for users to show that or skip it, and I decided to do that by distinguishing between 0 and 1 as a target.

This may have been a poor design decision, but Diogenes has behaved that way for about 15 years now, and I can guarantee that changing it will upset many users who have become accustomed to it, and some who depend upon it for the particular texts they use.  I acknowledge that it may not be an intuitive interface, and this is why there has always been that hint to users on the page.

Helma's suggestion of a separate button to show the proemial material would be great, except for cases where that material occurs at the start of each section rather than at the start of the work as a whole.  Then the interface would get complicated.

This was a conscious design decision, and like all such decisions, it was a matter of compromise between power and simplicity.  Your suggestion would simplify the interface but leave some users bereft of a feature that is useful to them.  I'm not convinced that there is a better compromise available, and even if there were, it would have to be much clearly better to overturn 15 years of user expectation.

I do appreciate your thoughtful input, and I always welcome suggestions to improve the interface.  Thanks for the feedback!

Peter
