### ISSUE TITLE
Entering capitalized Greek search term does not work

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#34]
The dispreferred diacritics can work in Greek, but capitals fail?

**Comment by pjheslin** [comment]
The problem with capitals was bound up with the problem with searching for accents, since in Beta code they are the same thing: i.e. capital letters are effectively indicated by a diacritic added to the letter.  Anyway, I've fixed both problems on Github, so you can now search for your preferred diacritics as well as for capitals.

I've added a tooltip to the search pages explaining the difference between loose and strict matching for Greek.  In the former, you don't enter accents or capitals and the search is insensitive to both.  In strict mode, which I've now reinstated, you specify accents and/or capitalization.  This with commit b8d2115, which will be in the next release.

Thanks for the report!

**Comment by helmadik** [comment]
Super!

Helma Dik
Department of Classics
University of Chicago
