### ISSUE TITLE
closing quotes included by parser

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#41]
In trying to compare the Lewis & Short display (and version) I tried profitetur and then cenamus in Plautus Captivi line 480-1

'quis ait “hoc” aut quis profitetur?' inquam. quasi muti silent, 
neque me rident. 'ubi cenamus?' inquam. átque illi abnuont. 

Response -
Could not parse profitetur', Could not parse cenamus' (ditto for 'ubi, but it lands just fine at the ubi entry)

Hoc in double quotation was fine.

**Comment by pjheslin** [comment]
This was an unintended consequence of a fix I made for a bug that you reported a few months ago where Diogenes was not correctly parsing elided forms in Greek.  I fixed that by leaving the apostrophes in place when parsing, but now I see that I need to take them out when parsing Latin.  Fixed in commit 1ad93a8e9c7563e9b2d06d548a3a1f0985c0424f

Furthermore, commit 70381f3eecc36b13c6d25f35667e9b09c8e0f216 fixes the problem with the treatment of y with an acute accent on the next page of text (_Captivi_, 506).
