### ISSUE TITLE
Sort works alphabetically

### ISSUE THREAD

**Issue by nivaca** [pjheslin/diogenes#47]
Would it be possible that the works of an author be sorted alphabetically? Currently, they are ordered rather randomly (or according to the databases' criterion). This makes looking for a certain work difficult. [See image](https://imgur.com/a/xSAsEq5)

Keep up the good work!

**Comment by pjheslin** [comment]
Sorry for the slow reply.  If you look again at that screenshot, you will see that the works of Cicero are not ordered randomly but in chronological order.  Of course, this is approximate and it does not make much sense to assign a single date to some of his works, such letter-collections, so this is not a perfect system.

As you say, this order just reflects the intrinsic numbering of the works in the database.  Since these numbers were not in fact chosen randomly, but have some principle behind them, I am not inclined to throw them away in favor of an alphabetical ordering. 

I'm a bit disappointed that the find-in-page function does not work in the box of titles.  I suppose that may be a bug in Electron, and if it is fixed eventually, that will provide a solution.
