### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by techvslife** [pjheslin/diogenes#58]
I'm trying to change "Amount of context to show in searches" from "paragraph" to "1 line."  Every time I save "1 line," it reverts back to "paragraph." (You can save "1 line" but it always uses "paragraph," and when you return to settings, it shows "paragraph.")  This is on Windows 10 x64.

**Comment by pjheslin** [comment]
Hmmm.  I just tested this on my Mac and it worked OK.  I'll have to borrow my wife's laptop to check it on Windows.

**Comment by techvslife** [comment]
Thanks, beyond not changing that setting, it also seems to want to always give three lines in the search results.  I thought it might have been the result of not running it with elevated (admin) privilege in Windows, but that appears to make no difference.

**Comment by pjheslin** [comment]
This is belatedly fixed in commit f46f42c670201460729cd14d395523d23fb3116e.  It was not a Windows-specific bug.  That was my mistake.  It was specific to the value "1 line".  Which actually gives you three lines, as it is designed to do: the line with the match and one before and one after.  Thanks for the report.
