### ISSUE TITLE
'find in page' boxes multiplying

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#63]
I sometimes end up with many of these; not sure if it's related to Diogenes sometimes becoming unresponsive (or is this grumpy behavior part of why you chose the name? I thought it was more benign:-))

**Comment by pjheslin** [comment]
This is because I simply forgot to check whether there was already a find box open when opening a new one.  The non-responsive behaviour with subsequent find boxes was a more frustrating bug to figure out, but it is fixed now with commit c09c6c52b9b64225163dab52db3dcb944db637aa.  Thanks for the report!
