### ISSUE TITLE
Filter names with accents don't render properly and cannot be deleted

### ISSUE THREAD

**Issue by bcdavasconcelos** [pjheslin/diogenes#71]
Hi,

filter names with accents don't render properly.   

Example:
```
Aristóteles
Platão
```

They also cannot be deleted for some reason. Attempts to do so result in a blank screen.

**Comment by pjheslin** [comment]
Thanks for the report.  I was aware of this problem, and I thought I had documented it in the FAQs, but I see now that I did not.  I tried to fix this at one point, but it turned out to be trickier than I thought.  Almost all of the code in Diogenes dates to a pre-Unicode era, so it's not always straight-forward to add Unicode.  I'll document this until I can fix it.

In the meantime, you can fix your problem by manually editing the diogenes.corpora file and substituting ASCII characters in those filter names.

**Comment by bcdavasconcelos** [comment]
Thanks for the feedback, @pjheslin. I will do as you suggested. Thanks again.
