### ISSUE TITLE
Make TLG/PHI settings discoverable in server-only mode.

### ISSUE THREAD

**Issue by MillerKrause** [pjheslin/diogenes#74]
The Electron app shows a splash screen that requests locations for TLG, PHI, and other data.  The standalone server, however, does not: starting up ./diogenes-server.pl results in no splash screen, and there is no obvious way to change data locations in the web page that does appear.  Diogenes 3.2 handled this with a link to a settings page; perhaps a similar link to the splash settings page might serve to make settings discoverable in 4.6?

**Comment by pjheslin** [comment]
Thanks -- this is a good point.  My emphasis in recent years has been to make Diogenes as simple as possible for non-technical users.  One of the main problems was getting them to input the path to the databases by hand in the settings page.  Fixing this by presenting the file-picker dialog box was one of the main considerations driving the development of the Electron client.  I removed the link to the settings page from the splash page because it was confusing some non-technical users and I hid it under the "Other settings" menu item.  But this made it invisible to those not using the Electron client.

In principle, it should be possible to detect when a user is not connecting from the Electron client, and to show the link to the settings page as part of the splash page to the old settings page to these users only.  I've added that to the to-do list.

A separate problem you report is that starting up ./diogenes-server.pl does not bring up the splash screen.  That does not happen when I test it, which is probably because, after running the Electron client, the config files are already in place on my machines.  In order to test this, I'll probably have to set up a virtual machine and install the server without running the client.

At the same time, I should try to reproduce issue #58

**Comment by pjheslin** [comment]
Here's a related bug, reported by email:

> Diogenes for Arch core dumps on updated Manjaro installation. However, the server works.
> I do own a copy of the TLG. But I can not find in the documentation where to set the TLGDIR for 
> diogenes-server. Could you please tell me where can I configure that and please add it to the documentation
> (or if it is already there, make it more visible) ?

Until I fix the link to the settings page, you can make a config file by hand with contents like this:

```
tlg_dir "/home/me/path/to/tlg/"
phi_dir "/home/me/path/to/phi/"
ddp_dir "/home/me/path/to/ddp/"

```
And for Linux, you can put it in: `~/.diogenes/diogenes.config`

**Comment by MillerKrause** [comment]
Thanks!  I suspect people looking to run the server-only Diogenes would be perfectly happy editing a config file manually for matters like setting directories, since there is rarely a need to change these settings, as long as a note to that effect is in the documentation somewhere.  For Mac, $config_dir seems to be ~/Library/Application\ Support/Diogenes/.  I was able to set up a new diogenes.config there (the old one from Diogenes 3 contained variables like cgi_font that are no longer used) and also drop in the old diogenes.corpora.  It worked nicely, at least for PHI.  I've got TLG working for "read" but not "search," but that is probably a different matter that I'll look into later.  Again, many thanks!
