### ISSUE TITLE
Problem with displaying text from Scholia in Platonem

### ISSUE THREAD

**Issue by chalkenteros** [pjheslin/diogenes#76]
It seems to be impossible to browse Scholia in Platonem (scholia vetera), Dialogue Mx, Stephanus page 235e.

Also, if I search for Aspasia in this text, the "Go to  context"-link from both results produces the message "Error: End of work reached without finding target citation!".

This in on Windows 10 x64.

**Comment by Doc73** [comment]
Same issue on Debian Bullseye/Sid AMD64.

Sorry, but the mention of Scholia in Platonem attracted me :laughing:

**Comment by pjheslin** [comment]
Sorry for the delay.  This is the same problem with the idt file as in issue #85. Fixed by commit 874d74cb77a7017baa6474bd28b61dca31f547a3.

Actually, I may disable this code for all authors in the forthcoming release, as it is an endless source of bugs.  With computers as fast as they are today, it is no longer such a problem to seek all the way through even the longest text for a citation.
