### ISSUE TITLE
Blank Window at Startup

### ISSUE THREAD

**Issue by VladKotenko** [pjheslin/diogenes#77]
When I start the program, the window is blank. Perhaps someone else had experienced a similar issue. Does anyone know how to configure the program so that it may work properly?

**Comment by pjheslin** [comment]
Sorry for the failure to respond.  When this happens it's usually because Diogenes has not been able to read the databases and an error message is usually printed to the terminal. I've just added an FAQ to the webpage with instructions on how to open a terminal and view the error message:
[Why does Diogenes crash/not work?](https://d.iogen.es/d/faqs.html)

**Comment by VladKotenko** [comment]
Thank you. I had that problem before reinstalling the system. After I installed Windows 11, the program started working normally.
