### ISSUE TITLE
Diogenes for MAC: ERROR 404 

### ISSUE THREAD

**Issue by TeaPrince1** [pjheslin/diogenes#9]
Hello!

When I click "Diogenes for MAC" I get the Error message: "This is not the webpage you are looking for"

Why?

Thank you for your attention
<img width="1112" alt="Screen Shot 2019-05-09 at 19 15 16" src="https://user-images.githubusercontent.com/50463102/57480388-7b8d5980-7297-11e9-8a3c-096b0ff01429.png">

**Comment by pjheslin** [comment]
Sorry about that.  I had changed the format of the mac filename without changing the Javascript on the website.  I've fixed it now. 

You will probably continue to see the error because your browser will have cached the erroneous Javascript.  So paste this URL into your browser: https://d.iogen.es/d/download.js
And then hit refresh.

**Comment by TeaPrince1** [comment]
Many thanks for your prompt response and for fixing the issue. It works very well! Congratulations!
